<?php
/**
 * @file
 * Code for the example module.
 */

/**
 * Theme hook
 */

function transferhub_vote_theme($existing, $type, $theme, $path) {
    return array('transferhub_vote_block' =>
        array(
            'variables' => array(
                'title' => null,
                'votes' => null,
                'form' => null,
                'voted' => null,
                'required_devices' => null,
                'deadline' => null,
            ),
            'template' => 'block--transferhubvoteblock'
        )
    );
}

