<?php

//todo això fa algo????
function transferhub_devicehub_action_info() {
    return array(
        'transferhub_devicehub_workflow_action' => array(
        'type' => 'node',
        'description' => t('Notify.'),
        'configurable' => TRUE,
        'behavior' => array('changes_node_property'),
        ),
    );
}

function transferhub_devicehub_user_insert($account)
{
    //Call DeviceHub
    $api = new  \Drupal\transferhub_devicehub\transferhub_DeviceHubRestClient();

    $base_url = "http://" . \Drupal::request()->getHost() . base_path();
    if (strpos(\Drupal::request()->getHost(), "localhost") !== false)
    {
        //todo
        $base_url = "http://www.reutilitza.cat/";
    }
    $user_url = $base_url. "user/".$account->id();

    $api->createUser( $user_url, $account->getEmail());
}

function transferhub_devicehub_node_insert(\Drupal\Core\Entity\EntityInterface $node)
{
    if ($node->getType() == "project") {
        //Call DeviceHub
        $api = new  \Drupal\transferhub_devicehub\transferhub_DeviceHubRestClient();

        $base_url = "http://" . \Drupal::request()->getHost() . base_path();
        if (strpos(\Drupal::request()->getHost(), "localhost") !== false)
        {
            //todo
            $base_url = "http://www.reutilitza.cat/";
        }

        //basic information
        $title = $node->getTitle();
        $desc = str_replace(array("\r", "\n"),"",strip_tags($node->get("field_description")->getValue()[0]["value"]));
        $shortDesc = str_replace(array("\r", "\n"),"",strip_tags($node->get("field_short_description")->getValue()[0]["value"]));
        $url = $base_url . "node/".$node->id();
        foreach($node->get("field_tags") as $term)
        {
            $term_id = $term->toArray()["target_id"];
            $term_name = \Drupal\taxonomy\Entity\Term::load($term_id)->toArray()["name"][0]["value"];
            $tags[] = $term_name;
        }
        $date = $node->get("field_deadline")->getValue()[0]["value"];
        if (isset($date) && !empty($date))
            $deadline = $date . "T00:00:00";

        $author_url = $base_url . "user/" . $node->get("uid")->getValue()[0]["target_id"];        

        if (\Drupal::moduleHandler()->moduleExists('transferhub_vote'))
        {
            $votes = \Drupal\transferhub_vote\Controller\TransferHubVoteController::getVotes($node->id());
        }
        else
            $votes = 0;

        $image_id = $node->get("field_image")->getValue()[0]["target_id"];
        $image = file_create_url(\Drupal\file\Entity\File::load($image_id)->getFileUri());
        $image = str_replace("localhost/reutilitza","www.reutilitza.cat", $image); //todo ESBORRAR

        //social
        $link_web = $node->get("field_website")->getValue()[0]["uri"];
        $link_fb = $node->get("field_facebook")->getValue()[0]["uri"];
        $link_twitter = $node->get("field_twitter")->getValue()[0]["uri"];

        //requipred equipment
        $count_desktop = $node->get("field_desktop")->getValue()[0]["value"];
        $count_desktop_peripherals = $node->get("field_desktop_with_peripherals")->getValue()[0]["value"];
        $count_laptop = $node->get("field_laptop")->getValue()[0]["value"];
        $count_phone = $node->get("field_mobile_phone")->getValue()[0]["value"];
        $count_tablet = $node->get("field_tablet_computer")->getValue()[0]["value"];
        $count_monitor = $node->get("field_computer_monitor")->getValue()[0]["value"];

        //address
        $address = $node->get("field_address")->getValue()[0];
        $addr_country = $address["country_code"];
        $addr_locality = $address["locality"];
        $addr_region = $address["administrative_area"];
        $addr_zip = $address["postal_code"];
        $addr_street = $address["address_line1"];

        //call DeviceHub
        $api->createProject(
        //basic information
            $title, $desc, $shortDesc, $url, $tags, $deadline, $author_url, $image,
            //social
            $link_web, $link_fb, $link_twitter, $votes,
            //required equipment
            $count_desktop, $count_desktop_peripherals, $count_laptop, $count_phone, $count_tablet, $count_monitor,
            //address
            $addr_country, $addr_locality, $addr_region, $addr_zip, $addr_street);
    }
}

