<?php

//todo això fa algo????
function transferhub_devicehub_action_info() {
    return array(
        'transferhub_devicehub_workflow_action' => array(
        'type' => 'node',
        'description' => t('Notify.'),
        'configurable' => TRUE,
        'behavior' => array('changes_node_property'),
        ),
    );
}

function transferhub_devicehub_user_insert($account)
{
    //Create new user in Devicehub
    \Drupal\transferhub_devicehub\TransferhubDevicehubTools::createUser($account);
}

function transferhub_devicehub_node_insert(\Drupal\Core\Entity\EntityInterface $node)
{
    if ($node->getType() == "project") {
        //Create new project in DeviceHub
        \Drupal\transferhub_devicehub\TransferhubDevicehubTools::createProject($node);
    }
}

