<?php

function transferhub_project_form_alter(&$form, \Drupal\Core\Form\FormStateInterface $form_state, $form_id)
{    
    if ($form_id == "node_project_edit_form" || $form_id == "node_project_form")
    {
        //Receivers can not edit list of ALLOCATED or RECEIVED devices in project node edition form
        $user = \Drupal::currentUser();
        if ( !in_array("manager",array_values($user->getRoles())) &&  !in_array("administrator",array_values($user->getRoles())) )
        {
            //allocation/reception
            unset($form["field_last_allocation"]);
            unset($form["field_allocated_devices"]);
            unset($form["field_last_reception"]);
            unset($form["field_received_devices"]);

            //project rating
            unset($form["field_use"]);
            unset($form["field_maintenance"]);
            unset($form["field_questionary"]);
            unset($form["field_reuse_return"]);
        }
    }
}

function transferhub_project_preprocess_page(&$variables) {

    $route_match = \Drupal::routeMatch();

    //Organization field display logic (in project edition forms)
    if ( //is project add form
        ($route_match->getRouteName() == "node.add" && $route_match->getRawParameter("node_type") == "project")
        //is project edit form
        || ($route_match->getRouteName() == "entity.node.edit_form" && $route_match->getParameter("node")->getType() == "project"))
    {
        $variables['#attached']['library'][] = 'transferhub_project/transferhub_project';
    }

    //Enables URL anchor navigation to subpages on load
    if ($route_match->getParameter("node") && $route_match->getParameter("node")->getType() == "page" &&  !$variables["is_front"]) {
        $variables['#attached']['library'][] = 'transferhub_project/anchor_scroll';
    }

    //Randomize advertisment display
    if ($route_match->getParameter("node") && $route_match->getParameter("node")->getType() == "project") {
        $variables['#attached']['library'][] = 'transferhub_project/random_advertisment';
    }

}
